{% set name = "pysmiles" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysmiles-{{ version }}.tar.gz
  sha256: 9bd1da9bf172fc79f71d647d21bbba34178702c664ae0778e59b4d4d149cbe4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=30.3.0
    - pbr
    - pip
  run:
    - python >={{ python_min }}
    - pbr
    - networkx

test:
  imports:
    - pysmiles
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pckroon/pysmiles
  summary: A lightweight SMILES reader and writer
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - awvwgk
