{% set name = "pysmiles" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysmiles-{{ version }}.tar.gz
  sha256: 587f745014e4a343b483a0f7f9c1dcf1da25ce88070ada3507c8fe998bee8016

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=30.3.0
    - pbr
    - pip
  run:
    - python >=3.6
    - pbr
    - networkx

test:
  imports:
    - pysmiles
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pckroon/pysmiles
  summary: A lightweight SMILES reader and writer
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - awvwgk
